### ISSUE TITLE
Memory leak - uses up large amounts of RAM for some users

### ISSUE THREAD

**Issue by mouseas** [mouseas/steamSummerMinigame#17]
Some users are reporting that when they use this script, their browser eats up memory at a ridiculous rate, indicating some sort of memory leak.

**Comment by wchill** [comment]
It actually has nothing to do with the script itself. The game is just full of memory leaks.

**Comment by wchill** [comment]
I double checked this yesterday when the game tab ate up 3.8GB and caused Chrome to crash.

**Comment by Gerarddp** [comment]
I can confirm that too, the script add a bit of overhead but is not the cause.

**Comment by Eriner** [comment]
Indeed, I have benchmarked two tabs (one with the script, one without), and RAM usage is very similar.

**Comment by BKPepe** [comment]
I can confirm this too. It caused Firefox to crash atleast 4 times.

**Comment by mouseas** [comment]
It seems the particles (and graphics in general) are the culprit. I've been told that some particles aren't being destroyed properly, so they just build up over time.

Players using auto-clickers have been hit the worst, since each click emits a bunch of particles.

However, we might be able to help the situation if we add some code to clean up particles, e.g. calling `destroy()` on every particle whether it's expired or not, or modifying the game's particle emitter code to no longer emit particles in the first place.

**Comment by wchill** [comment]
I talked with someone in Steam chat who suggested removing the particle effects, apparently there are still memory leaks but they are vastly improved. Well worth implementing as an option.

**Comment by Eriner** [comment]
I put one vote in to remove the effects altogether; remove the source rather than 'fix' it.

**Comment by mouseas** [comment]
@wchill Got an implementation? I know some of the auto-clickers are bypassing `DoClick()` to avoid visual effects, but since this script doesn't click, that doesn't help.

**Comment by wchill** [comment]
```
2:20 PM - Meepen [aim-flex]: well basically what i did was stop 
CSceneGame.prototype.SpawnEmitter 

and
CSceneGame.prototype.DoClickEffect 
from running
```

I assume stubbing those out should do the trick.

**Comment by wchill** [comment]
```
window.g_Minigame.CurrentScene().DoClickEffect = function() {};
window.g_Minigame.CurrentScene().SpawnEmitter = function() {};
```

**Comment by mouseas** [comment]
@wchill Glorious, that works ~~flawlessly~~! Thanks!

I've just added that to the top of the script.

**Comment by mouseas** [comment]
Ok, it's not flawless. It causes an error in the game code, `junning.js:979`. Let's see if we can fix this!

**Comment by Contex** [comment]
@mouseas see my comment in 5b0aacef876dc833d983eeaaa13e86d8a1347742

**Comment by mouseas** [comment]
@Contex - Awesome, I'm getting to errors in the console so far. Thanks!

**Comment by Contex** [comment]
@mouseas glad to hear, no problem!
