### ISSUE TITLE
Auto purchase upgrades and abilities

### ISSUE THREAD

**Issue by Xinayder** [mouseas/steamSummerMinigame#19]
- ~~Auto click should be added;~~
- It should purchase the auto cannon and the click upgrades automatically if it has the money;
- ~~Attack 3 targets at a time?~~

**Comment by mouseas** [comment]
Auto click is against the purpose of this script. Excellent auto click scripts exist elseware, and can run alongside this script.

Purchasing upgrades and abilities is on the TODO list.

Attacking 3 targets is also against the purpose of this script, for the same reason.

**Comment by Gerarddp** [comment]
Auto click won't be added as @mouseas request, if you want it go to https://github.com/wchill/steamSummerMinigame or https://github.com/Gerarddp/steamSummerMinigame

**Comment by Xinayder** [comment]
Why is autoclicking against the purpose of this script? It is the same thing as executing this script twice.

**Comment by mouseas** [comment]
I'm trying to keep the script within the bounds of what a human player can do, and I also don't want it to get players banned or cause Valve to respond. Auto-clicking, especially far more than a human could do, is likely to cause Valve to patch the game or ban players. I'm not opposed to people using an auto-clicker, but I'm not going to include it in my script.

**Comment by ZedTheYeti** [comment]
My idea for auto purchasing would be that we decide on upgrades that are important and upgrade them in rounds. So at low level we upgrade Light Armor if we can, then Auto-fire Cannon if we can, then Armor Piercing Round if we can, after that we repeat. Once new upgrades are available we switch to that and start doing rounds of upgrading them. Thoughts?

**Comment by Xinayder** [comment]
And then try to keep all upgrades in the same level.

**Comment by ZedTheYeti** [comment]
Exactly, for nice even upgrades. Don't move on to the next "tier" until they're all the same. It may not be the most effective way to do it, but it's fairly simple.

**Comment by Ruzihm** [comment]
Handling the tiers is pretty easy. Each one is 10x the previous one so you
compare the price of tier 1, the price of tier 2 divided by 10, and the
price of tier 3 divided by 100 and pick the lowest.

**Comment by mouseas** [comment]
We'll want to buy abilities alongside upgrades. Medics should be one of the first purchases after a few armor + autocannon upgrades.

Also, since the script doesn't auto-click, we should reduce the importance of click damage upgrades (with an easy method to bring it up to on par with auto-damage upgrades for people using an auto-clicker).

**Comment by Xinayder** [comment]
Just read this in the readme:

> Automatic clicking pushes into the area of cheating, and this script is not designed for cheating.

Auto-purchasing/farming by gold is also cheating. So, why not include the auto-click? Create a new branch for it.

**Comment by Eriner** [comment]
@RockyTV This is a fork with auto-clicking: https://github.com/wchill/steamSummerMinigame

@mouseas doesn't want to implement it, so leave it be. Use that fork if you must.

**Comment by russeli** [comment]
How should the elemental damage be valued?
p =  odds of element appearing atleast in one lane
p*cost/multiplier?

**Comment by ghost** [comment]
I think the elemental damage should be considered alongside the damage upgrades. Perhaps a basic level 2 for each element somewhere in the first few purchases (it does help a lot), then some more strategic planning as the game progresses. 

Perhaps the importance of click damage upgrades vs autocannon should be up to a true/false at the top indicating if the user prefers auto clicking? Also, the value of having autocannon upgrades should be evaluated in relation to the damage it could provide against the amount of damage the user can deal using clicks. 

i.e. $10000 for +10 dmg/click upgrade vs $800 for + 10 dmg/sec upgrade 
dmg/click @ 10 clicks-per-second average = $10000/(10 clicks \* 10 dmg) = $100/1 dps
dmg/sec  = $800/10 dmg = $80/1 dps

As you can see above, the autocannon would be the superior upgrade.
**Edit:** formatting

**Comment by ghost** [comment]
Also, something else I just thought of. Some way to prioritize and auto-purchase the one-use badge abilities at the beginning of each day (see table at bottom of [relevant link](http://www.reddit.com/r/Steam/comments/39i0qc/psa_how_the_monster_game_works_an_indepth/)). I'd assume the gold-per-click would be one of the best ones to get, but perhaps the others could be prioritized in some way. This would also involve an efficient auto-use of those abilities as well, but that's for another thread.

**Comment by mouseas** [comment]
@JCKE - about auto-purchasing reward items - raise it as a new issue (`enhancement` and `help wanted`).

**Comment by Kline-** [comment]
This seems to have been added in f1c54b239379496cb09a0a9c8ed19aa0d3ba52f3; can we please get a way to disable it? I re-opened the game this morning with almost enough for a new rank of AFK Gear and the auto-purchaser spent everything on manual click upgrades. I don't even click outside of raining gold, so how is that at all useful?

**Comment by LMariachi** [comment]
@Kline- Comment out (or delete) the `purchaseUpgrades();` line from `function doTheThing();`

(This will disable all auto-purchasing except for initial badge items. Disabling only the click upgrades is a little more involved.)

**Comment by russeli** [comment]
Disabling clicking upgrades can be done by changing the `avgClicksPerSecond` variable to 0

**Comment by win0na** [comment]
I have added a toggle in https://github.com/mouseas/steamSummerMinigame/commit/ff4ccc598a3b9b20ea9ea28c771d6bf10a0c16d2.
