### ISSUE TITLE
Auto purchase badge-point reward items each day

### ISSUE THREAD

**Issue by ghost** [mouseas/steamSummerMinigame#52]
https://github.com/mouseas/steamSummerMinigame/issues/19#issuecomment-111658489
Should check if reward items are purchasable, and prioritize how to efficiently spend badge points amongst them. Something I thought I remembered reading somewhere was a limit of 25 of each, but you'll have to double check that.

**Comment by ZedTheYeti** [comment]
I'm assuming we'll be able to detect it the same way we do the respawn menu. So we just need to figure out how to buy them, how to determine how many points we have, and come up with a plan on which to upgrade. Some people looking at this code when it comes up tomorrow would be really helpful. Though we could just pick through the source as well.

**Comment by ghost** [comment]
I've been picking through the source my self in-between working on some pull requests, and it seems fairly simple. The only tricky thing will be testing I suppose. 

**EDIT:** working on right now [over on my repo](https://github.com/JCKE/steamSummerMinigame/tree/badgePoints). Feel free to join in!

**Comment by ghost** [comment]
So this has been fully implemented, and the issue can probably be closed. I think we should still weight the distribution of what is bought, though

**Comment by win0na** [comment]
If you feel the need to start up a discussion over what is specifically bought, go ahead. This issue has been resolved.
