### ISSUE TITLE
Game allegedly includes autoclick detection 

### ISSUE THREAD

**Issue by Robadob** [mouseas/steamSummerMinigame#56]
http://www.reddit.com/r/SteamMonsterGame/comments/39ny04/monster_game_seems_to_have_built_in/
Apparently Clicks/ps is capped at 18.2, but this degrades down to 0.5 if you don't move your mouse. Can't confirm myself, but it's worth a look at, had a few people contact me to ask for script to be updated to include it.

**Comment by kiradotee** [comment]
Comments there suggest to disable the check for mouse movement AND/OR to set g_msTickRate =1100;

**Comment by mouseas** [comment]
Since this script itself doesn't include an auto-clicker, and every suggestion I've made to other developers recommends no more than 10 clicks/sec, I don't think it's an issue for this script.

**Comment by win0na** [comment]
This pull request (https://github.com/mouseas/steamSummerMinigame/pull/69) implements a workaround by resetting g_msTickRate every single time the script clicks in the gold rain clicker. Therefore, it bypasses the autoclick detection.
