### ISSUE TITLE
Switch to the lane with a boss?

### ISSUE THREAD

**Issue by kiradotee** [mouseas/steamSummerMinigame#57]
Mine sometimes goes away from that lane.

**Comment by mouseas** [comment]
The code is supposed to prefer the boss lane. Has anyone else experienced it switching away from the boss before the boss dies?

**Comment by win0na** [comment]
No, I've never experienced that.

**Comment by regener** [comment]
Yes, it does leave the lane before the boss dies so I get no gold for it.
I think the clients gets slower the information about the boss's current state (alive or dead) then expected, so the script leaves the lane because it thinks the boss is dead.

Maybe if you can wait for gold to increase then switch lane should help.

**Comment by AlexLeporiday** [comment]
I too have witnessed the lane switch during a boss but not very frequently.

**Comment by oedw** [comment]
Could it have something to do with this now? https://github.com/wchill/steamSummerMinigame/issues/118

My boss id is 0, not 2 :/

**Comment by ghost** [comment]
Maybe wait a second after the client thinks it's dead before switching?

**Comment by Aeruja** [comment]
It probably switches lane to kill off a weakened enemy or that an minion got hit with a falling gold before the boss does..though those few seconds of switching could mean the difference of 100k vs 100m

**Comment by regener** [comment]
JCKE: I have tried that with a check of lasttartget (should be ENEMY_TYPE.BOSS) and current one (should be one from the other ENEMY_TYPE-s), but it fails to detect.

**Comment by ozerugae** [comment]
@regener by lasttarget do you mean: m_nTarget?

**Comment by regener** [comment]
Not really, I am new to scripting so I though that would do it: (and don't laugh if I made it wrong xD)

```
    var enemy = g_Minigame.m_CurrentScene.GetEnemy(g_Minigame.m_CurrentScene.m_rgPlayerData.current_lane, g_Minigame.m_CurrentScene.m_rgPlayerData.target);
    if (enemy && enemy.m_data.type == ENEMY_TYPE.BOSS)
    {
        targetIsBoss = true;
    } else {
        targetIsBoss = false;
    }

    if (enemy && enemy.m_data.type != ENEMY_TYPE.BOSS)
    {
        currentTargetIsBoss = true;
    } else {
        currentTargetIsBoss = false;
    }   
    var lastTargetIsBoss = false;
    if( targetIsBoss == true ) {
        lastTargetIsBoss = true;
    }
    if( lastTargetIsBoss == true  && currentTargetIsBoss == false) {
        setTimeout(function (){
            console.log("---------- Boss or Treasure money drop delay ----------");
            lastTargetIsBoss = false;
            currentTargetIsBoss = false;
            g_Minigame.CurrentScene().TryChangeLane(lowLane);
        }, 1000);
    }
    else {
        g_Minigame.CurrentScene().TryChangeLane(lowLane);
    }
```

**Comment by ozerugae** [comment]
It's a learning experience; we all started there ;)

``` javascript
    if (enemy && enemy.m_data.type == ENEMY_TYPE.BOSS)
    {
        targetIsBoss = true;
    } else {
        targetIsBoss = false;
    }

    if (enemy && enemy.m_data.type != ENEMY_TYPE.BOSS)
    {
        currentTargetIsBoss = true;
    } else {
        currentTargetIsBoss = false;
    } 
```

can be condensed to

``` javascript
    if (enemy && enemy.m_data.type == ENEMY_TYPE.BOSS)
    {
        targetIsBoss = true;
        currentTargetIsBoss = false;        
    } else {
        targetIsBoss = false;
        currentTargetIsBoss = true;
    }
```

However, I can't see how the code will work as the moment the target changes, the lane would change as there is only one target in the boss lane. Or maybe I am missing something?

I would just check whether the boss is dead and then only allow the lane to change. You can do that by looping through g_Minigame.CurrentScene().m_rgEnemies , finding the boss by checking g_Minigame.CurrentScene().m_rgEnemies[].m_data.type. If the boss' hp is 0, the boss is dead.

or with no loop using the code you provided:

``` javascript
var enemy = g_Minigame.m_CurrentScene.GetEnemy(g_Minigame.m_CurrentScene.m_rgPlayerData.current_lane, g_Minigame.m_CurrentScene.m_rgPlayerData.target);
    if (enemy && enemy.m_data.type == ENEMY_TYPE.BOSS){
        if(enemy.m_data.hp == 0)
        //boss is dead :o
}

```

**Comment by regener** [comment]
So I have this now, but it doesn't work, atleast I got no console log.

``` javascript
if (g_Minigame.CurrentScene().m_nExpectedLane != lowLane) {
// check for last target and sleep if we wait for boss money, else switch lane instantly
    var enemy = g_Minigame.m_CurrentScene.GetEnemy(g_Minigame.m_CurrentScene.m_rgPlayerData.current_lane, g_Minigame.m_CurrentScene.m_rgPlayerData.target);
    if (enemy && enemy.m_data.type == ENEMY_TYPE.BOSS && enemy.m_data.hp == 0){
            setTimeout(function (){
                console.log("---------- Boss or Treasure money drop delay ----------");
                g_Minigame.CurrentScene().TryChangeLane(lowLane);
            }, 1000);
    }
    else {
        //console.log("Delay not working or last target is not a boss");
        g_Minigame.CurrentScene().TryChangeLane(lowLane);
    }
}
```

@JCKE got it, thanks

**Comment by ghost** [comment]
@regener could you please wrap that in markdown code using 3 ` before and after it? Also, using keyword javascript after the first set of 3 gives it color coding

**Comment by ozerugae** [comment]
Where did you place the code?

Try this for debugging (added an output to console.log on the second line):

``` javascript
if (g_Minigame.CurrentScene().m_nExpectedLane != lowLane) {
console.log("is g_Minigame.CurrentScene().m_nExpectedLane != lowLane ever true?");
// check for last target and sleep if we wait for boss money, else switch lane instantly
    var enemy = g_Minigame.m_CurrentScene.GetEnemy(g_Minigame.m_CurrentScene.m_rgPlayerData.current_lane, g_Minigame.m_CurrentScene.m_rgPlayerData.target);
    if (enemy && enemy.m_data.type == ENEMY_TYPE.BOSS && enemy.m_data.hp == 0){
            setTimeout(function (){
                console.log("---------- Boss or Treasure money drop delay ----------");
                g_Minigame.CurrentScene().TryChangeLane(lowLane);
            }, 1000);
    }
    else {
        //console.log("Delay not working or last target is not a boss");
        g_Minigame.CurrentScene().TryChangeLane(lowLane);
    }
}
```

You can also do 

``` javascript
console.log("Result of expectedLane == lowLane: " + g_Minigame.CurrentScene().m_nExpectedLane != lowLane);
```

a line before the beginning of your code to check whether that will evaluate to true correctly when needed.

**Comment by regener** [comment]
I have placed it where the

``` javascript
// go to the chosen lane
    if (targetFound) {
```

Is starting and replacing the default change lane method.

This spams "true" to the console.

``` javascript
console.log("Result of expectedLane == lowLane: " + g_Minigame.CurrentScene().m_nExpectedLane != lowLane);
```

Also yes, this shows up in console:

``` javascript
console.log("is g_Minigame.CurrentScene().m_nExpectedLane != lowLane ever true?");
```

I think this detection does not work, since there is no console log shown.

``` javascript
 if (enemy && enemy.m_data.type == ENEMY_TYPE.BOSS && enemy.m_data.hp == 0){
```

Can I somehow print out the Boss's HP to console?
Yea, got it:

``` javascript
var enemy = g_Minigame.m_CurrentScene.GetEnemy(g_Minigame.m_CurrentScene.m_rgPlayerData.current_lane, g_Minigame.m_CurrentScene.m_rgPlayerData.target);
            console.log("Enemy HP: " +enemy.m_data.hp);
```

**Comment by luxzg** [comment]
Yeah, when boss is alive and until it's 100% sure we got the money, script shouldn't leave. +1 for solving this

**Comment by regener** [comment]
The main problem is sometimes the levels are changing faster than the script runs (lol).
For example I have started today's run and I see Level is jumping up with 2lvl/sec atleast, sometimes more xD

**Comment by mouseas** [comment]
Can someone give me a tl;dr of whether this is confirmed and/or if a fix has been created?

**Comment by regener** [comment]
Since not too many users had that yet, _I think_ you can close this.
