### ISSUE TITLE
Label already declared

### ISSUE THREAD

**Issue by brickmaster32000** [mouseas/steamSummerMinigame#6]
When attempting to copy the script into either firefox or chrome I get the following error.

Uncaught SyntaxError: Label 'https' has already been declared
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)

**Comment by mouseas** [comment]
What did you copy? My first guess is you might have opened the file here in github and copied the entire web page, not just the javascript code.

**Comment by brickmaster32000** [comment]
Ah found the problem noscript was adding a couple extra lines to the end of the file.
