### ISSUE TITLE
Losing extra money from Gold Rain

### ISSUE THREAD

**Issue by Insferatu** [mouseas/steamSummerMinigame#60]
Right now hit animation and damage are not shown. On the Boss level Gold Rains are activated, but no extra money added, it looks like "There is no hit animantion, which means you doesn't hit monster, which means you don't receive extra gold during Gold Rain".

**Comment by mouseas** [comment]
Gold Rain requires you to click to benefit from it. The text animation for gold gained is _not_ suppressed, so you should still see the yellow text when clicking while Gold Rain is active. If that's not happening, re-open this issue.
