### ISSUE TITLE
Go to lane with a chest if available

### ISSUE THREAD

**Issue by Gerarddp** [mouseas/steamSummerMinigame#8]

**Comment by josefwells** [comment]
Similarly, go to a lane with "Raining Gold", probably only if there is a spawner/boss left

**Comment by xPaw** [comment]
It should also target based on elemental upgrades.

**Comment by mouseas** [comment]
I'll leave this for someone else to implement.

Note that Raining Gold doesn't affect this script since the script doesn't auto-click and Raining Gold relies on actively clicking enemies.

**Comment by mouseas** [comment]
@Gerarddp - Are the chests you're referring to Treasure Minions? If so, the latest version targets them first, which would mean this issue is already fixed.

**Comment by Gerarddp** [comment]
Yes, thank you. For all the other issues in this thread see #13 and #15
