### ISSUE TITLE
Modify auto purchase

### ISSUE THREAD

**Issue by Torsdan** [mouseas/steamSummerMinigame#91]
Is there a way to disable the purchasing or lower the value of click dmg upgrades? As I'm only interested in Health, Auto Cannon and Elemental Dmg.

**Comment by gapple** [comment]
within `purchaseUpgrades()`, change the `avgClicksPerSecond` variable.

`0` will disable purchasing click upgrades, or just choose a fraction for a different balance (I have been using 1/100 in early game)

**Comment by Torsdan** [comment]
Thanks @gapple
