### ISSUE TITLE
Variables renamed ? Valve forced refresh and the script is barelly working right now ?

### ISSUE THREAD

**Issue by leontada** [mouseas/steamSummerMinigame#95]
It happened 5minutes ago, and checking de CONSOLE LOG it says that the js cant find the variable LEVEL.

**Comment by gapple** [comment]
The problem appears to be that `g_Minigame.CurrentScene().m_rgPlayerUpgrades` is missing an item, so that its indexes don't match the data it contains anymore, which was assumed by the upgrade function.

**Comment by russeli** [comment]
There's now pull request(#96) pending to fix this issue.

**Comment by leontada** [comment]
I tested your pull request and it worked perfectly! :+1:

**Comment by win0na** [comment]
Apologies for the wait. The specified pull request has been merged after looking it over.
